name: Release Executable

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Sista dependency
        uses: actions/checkout@v4
        with:
          repository: FLAK-ZOSO/Sista
          path: Sista
          ref: main
          fetch-depth: 0

      - name: Install Sista
        if: matrix.os != 'windows-latest'
        run: |
          cd Sista
          sudo make install
          cd ..

      - name: Install Sista (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          cd Sista
          make install
          cd ..

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run make
        run: make

      - name: Find Executable
        id: find-exe
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            echo "exe_path=$(find . -type f -name 'dodas.exe' | head -n 1)" >> $GITHUB_OUTPUT
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            echo "exe_path=$(find . -name dodas -type f -perm +111 | head -n 1)" >> $GITHUB_OUTPUT
          else
            echo "exe_path=$(find . -name dodas -type f -perm /111 | head -n 1)" >> $GITHUB_OUTPUT
          fi

      - name: Rename executable (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          mv "${{ steps.find-exe.outputs.exe_path }}" "dodas-${{ runner.os }}"

      - name: Rename executable (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Move-Item -Path "${{ steps.find-exe.outputs.exe_path }}" -Destination "dodas-${{ runner.os }}.exe"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dodas-${{ runner.os }}*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
